import {Color, Vector} from 'excalibur';

const circuits = {};

class CircuitData {
	name; // : string = id of the circuit
	trackWidth; // : number = width of asphalt
	grassWidth; // : number = width of grass exceeding asphalt on either side
	waypoints; // : array = {x : number, y : number, checkpoint : boolean, start : boolean, finish : boolean}
	requiredCheckpoints; // : number (amount of checkpoints in this circuit)
	color; // : excalibur color object

	constructor(name, trackWidth, grassWidth, requiredCheckpoints, color, waypoints) {
		this.name = name;
		this.trackWidth = trackWidth;
		this.grassWidth = grassWidth;
		this.waypoints = waypoints;
		this.requiredCheckpoints = requiredCheckpoints;
		this.color = color;
	}

	getTrackJointsData() {
		const jointsData = [];
		this.waypoints.forEach((waypoint, index) => {
			const {x, y, checkpoint, start, finish} = waypoint;
			const next = (({x, y}) => ({x, y}))(this.waypoints[index + 1] || this.waypoints[0]);
			const rotation = Math.atan2(y - next.y, x - next.x);
			jointsData.push({
				pos: new Vector(x, y),
				rotation,
				checkpoint,
				start,
				finish,
				radius: this.trackWidth / 2,
				color: this.color,
				grassWidth: this.grassWidth
			});
		});
		return jointsData;
	}

	getTrackStraightsData() {
		const straightsData = [];
		this.waypoints.forEach((waypoint, index) => {
			const a = (({x, y}) => ({x, y}))(waypoint);
			const b = (({x, y}) => ({x, y}))(this.waypoints[index + 1] ?? this.waypoints[0]);
			const distance = Vector.distance(a, b);
			const rotation = Math.atan2(b.y - a.y, b.x - a.x);
			straightsData.push({
				pos: new Vector(a.x, a.y),
				distance,
				rotation,
				trackWidth: this.trackWidth,
				grassWidth: this.grassWidth,
				color: this.color
			});
		});
		return straightsData;
	}
}

circuits['spa-francorchamps'] = new CircuitData('spa-francorchamps', 130, 38, 3, Color.fromHex('#282525'), [
	{x: 897, y: 2050, checkpoint: false, start: true, finish: true},
	{x: 695, y: 2189, checkpoint: false, start: false, finish: false},
	{x: 229, y: 2491, checkpoint: false, start: false, finish: false},
	{x: 177, y: 2525, checkpoint: false, start: false, finish: false},
	{x: 120, y: 2535, checkpoint: false, start: false, finish: false},
	{x: 97, y: 2491, checkpoint: false, start: false, finish: false},
	{x: 225, y: 2209, checkpoint: false, start: false, finish: false},
	{x: 252, y: 2155, checkpoint: false, start: false, finish: false},
	{x: 280, y: 2100, checkpoint: false, start: false, finish: false},
	{x: 310, y: 2045, checkpoint: false, start: false, finish: false},
	{x: 342, y: 1990, checkpoint: false, start: false, finish: false},
	{x: 377, y: 1940, checkpoint: false, start: false, finish: false},
	{x: 416, y: 1893, checkpoint: false, start: false, finish: false},
	{x: 460, y: 1848, checkpoint: false, start: false, finish: false},
	{x: 504, y: 1805, checkpoint: false, start: false, finish: false},
	{x: 811, y: 1502, checkpoint: false, start: false, finish: false},
	{x: 856, y: 1458, checkpoint: false, start: false, finish: false},
	{x: 891, y: 1409, checkpoint: false, start: false, finish: false},
	{x: 918, y: 1354, checkpoint: false, start: false, finish: false},
	{x: 952, y: 1301, checkpoint: false, start: false, finish: false},
	{x: 994, y: 1256, checkpoint: false, start: false, finish: false},
	{x: 1046, y: 1222, checkpoint: false, start: false, finish: false},
	{x: 1103, y: 1200, checkpoint: false, start: false, finish: false},
	{x: 1163, y: 1185, checkpoint: false, start: false, finish: false},
	{x: 1225, y: 1175, checkpoint: false, start: false, finish: false},
	{x: 1278, y: 1146, checkpoint: false, start: false, finish: false},
	{x: 1329, y: 1112, checkpoint: false, start: false, finish: false},
	{x: 1675, y: 852, checkpoint: false, start: false, finish: false},
	{x: 1725, y: 815, checkpoint: false, start: false, finish: false},
	{x: 1776, y: 782, checkpoint: false, start: false, finish: false},
	{x: 1830, y: 750, checkpoint: false, start: false, finish: false},
	{x: 1884, y: 724, checkpoint: false, start: false, finish: false},
	{x: 1943, y: 700, checkpoint: false, start: false, finish: false},
	{x: 2001, y: 681, checkpoint: false, start: false, finish: false},
	{x: 2059, y: 662, checkpoint: false, start: false, finish: false},
	{x: 3279, y: 195, checkpoint: true, start: false, finish: false},
	{x: 3337, y: 173, checkpoint: false, start: false, finish: false},
	{x: 3396, y: 158, checkpoint: false, start: false, finish: false},
	{x: 3457, y: 163, checkpoint: false, start: false, finish: false},
	{x: 3507, y: 200, checkpoint: false, start: false, finish: false},
	{x: 3547, y: 245, checkpoint: false, start: false, finish: false},
	{x: 3600, y: 275, checkpoint: false, start: false, finish: false},
	{x: 3661, y: 266, checkpoint: false, start: false, finish: false},
	{x: 3717, y: 239, checkpoint: false, start: false, finish: false},
	{x: 3773, y: 216, checkpoint: false, start: false, finish: false},
	{x: 3833, y: 198, checkpoint: false, start: false, finish: false},
	{x: 3894, y: 199, checkpoint: false, start: false, finish: false},
	{x: 3944, y: 233, checkpoint: false, start: false, finish: false},
	{x: 3987, y: 278, checkpoint: false, start: false, finish: false},
	{x: 4311, y: 650, checkpoint: false, start: false, finish: false},
	{x: 4350, y: 698, checkpoint: false, start: false, finish: false},
	{x: 4375, y: 755, checkpoint: false, start: false, finish: false},
	{x: 4369, y: 815, checkpoint: false, start: false, finish: false},
	{x: 4327, y: 859, checkpoint: false, start: false, finish: false},
	{x: 4268, y: 876, checkpoint: false, start: false, finish: false},
	{x: 4209, y: 859, checkpoint: false, start: false, finish: false},
	{x: 4166, y: 815, checkpoint: false, start: false, finish: false},
	{x: 4128, y: 768, checkpoint: false, start: false, finish: false},
	{x: 4052, y: 669, checkpoint: false, start: false, finish: false},
	{x: 4014, y: 621, checkpoint: false, start: false, finish: false},
	{x: 3962, y: 591, checkpoint: false, start: false, finish: false},
	{x: 3902, y: 598, checkpoint: false, start: false, finish: false},
	{x: 3845, y: 617, checkpoint: false, start: false, finish: false},
	{x: 3083, y: 861, checkpoint: true, start: false, finish: false},
	{x: 3023, y: 877, checkpoint: false, start: false, finish: false},
	{x: 2965, y: 898, checkpoint: false, start: false, finish: false},
	{x: 2913, y: 931, checkpoint: false, start: false, finish: false},
	{x: 2870, y: 975, checkpoint: false, start: false, finish: false},
	{x: 2850, y: 1033, checkpoint: false, start: false, finish: false},
	{x: 2845, y: 1095, checkpoint: false, start: false, finish: false},
	{x: 2845, y: 1157, checkpoint: false, start: false, finish: false},
	{x: 2849, y: 1218, checkpoint: false, start: false, finish: false},
	{x: 2863, y: 1278, checkpoint: false, start: false, finish: false},
	{x: 2884, y: 1335, checkpoint: false, start: false, finish: false},
	{x: 2918, y: 1387, checkpoint: false, start: false, finish: false},
	{x: 2966, y: 1426, checkpoint: false, start: false, finish: false},
	{x: 3019, y: 1459, checkpoint: false, start: false, finish: false},
	{x: 3075, y: 1484, checkpoint: false, start: false, finish: false},
	{x: 3134, y: 1503, checkpoint: false, start: false, finish: false},
	{x: 3194, y: 1518, checkpoint: false, start: false, finish: false},
	{x: 3667, y: 1655, checkpoint: false, start: false, finish: false},
	{x: 3726, y: 1675, checkpoint: false, start: false, finish: false},
	{x: 3778, y: 1704, checkpoint: false, start: false, finish: false},
	{x: 3818, y: 1753, checkpoint: false, start: false, finish: false},
	{x: 3829, y: 1813, checkpoint: false, start: false, finish: false},
	{x: 3817, y: 1873, checkpoint: false, start: false, finish: false},
	{x: 3794, y: 1931, checkpoint: false, start: false, finish: false},
	{x: 3777, y: 1989, checkpoint: false, start: false, finish: false},
	{x: 3782, y: 2051, checkpoint: false, start: false, finish: false},
	{x: 3809, y: 2106, checkpoint: false, start: false, finish: false},
	{x: 3859, y: 2143, checkpoint: false, start: false, finish: false},
	{x: 3911, y: 2174, checkpoint: false, start: false, finish: false},
	{x: 4079, y: 2253, checkpoint: false, start: false, finish: false},
	{x: 4135, y: 2278, checkpoint: false, start: false, finish: false},
	{x: 4188, y: 2309, checkpoint: false, start: false, finish: false},
	{x: 4237, y: 2348, checkpoint: false, start: false, finish: false},
	{x: 4270, y: 2399, checkpoint: false, start: false, finish: false},
	{x: 4270, y: 2461, checkpoint: false, start: false, finish: false},
	{x: 4242, y: 2516, checkpoint: false, start: false, finish: false},
	{x: 4208, y: 2568, checkpoint: false, start: false, finish: false},
	{x: 4155, y: 2648, checkpoint: false, start: false, finish: false},
	{x: 4118, y: 2696, checkpoint: false, start: false, finish: false},
	{x: 4072, y: 2738, checkpoint: false, start: false, finish: false},
	{x: 4016, y: 2763, checkpoint: false, start: false, finish: false},
	{x: 3954, y: 2768, checkpoint: false, start: false, finish: false},
	{x: 3893, y: 2762, checkpoint: false, start: false, finish: false},
	{x: 3833, y: 2749, checkpoint: false, start: false, finish: false},
	{x: 3773, y: 2731, checkpoint: false, start: false, finish: false},
	{x: 3658, y: 2687, checkpoint: false, start: false, finish: false},
	{x: 3550, y: 2627, checkpoint: false, start: false, finish: false},
	{x: 3451, y: 2553, checkpoint: false, start: false, finish: false},
	{x: 3359, y: 2471, checkpoint: false, start: false, finish: false},
	{x: 3234, y: 2334, checkpoint: false, start: false, finish: false},
	{x: 3093, y: 2134, checkpoint: true, start: false, finish: false},
	{x: 2989, y: 1981, checkpoint: false, start: false, finish: false},
	{x: 2949, y: 1932, checkpoint: false, start: false, finish: false},
	{x: 2905, y: 1889, checkpoint: false, start: false, finish: false},
	{x: 2855, y: 1853, checkpoint: false, start: false, finish: false},
	{x: 2802, y: 1824, checkpoint: false, start: false, finish: false},
	{x: 2747, y: 1796, checkpoint: false, start: false, finish: false},
	{x: 2690, y: 1771, checkpoint: false, start: false, finish: false},
	{x: 2633, y: 1748, checkpoint: false, start: false, finish: false},
	{x: 2575, y: 1728, checkpoint: false, start: false, finish: false},
	{x: 2516, y: 1709, checkpoint: false, start: false, finish: false},
	{x: 2455, y: 1693, checkpoint: false, start: false, finish: false},
	{x: 2396, y: 1679, checkpoint: false, start: false, finish: false},
	{x: 2335, y: 1669, checkpoint: false, start: false, finish: false},
	{x: 2274, y: 1668, checkpoint: false, start: false, finish: false},
	{x: 2214, y: 1678, checkpoint: false, start: false, finish: false},
	{x: 2155, y: 1702, checkpoint: false, start: false, finish: false},
	{x: 2101, y: 1729, checkpoint: false, start: false, finish: false},
	{x: 1883, y: 1847, checkpoint: false, start: false, finish: false},
	{x: 1829, y: 1874, checkpoint: false, start: false, finish: false},
	{x: 1771, y: 1896, checkpoint: false, start: false, finish: false},
	{x: 1712, y: 1913, checkpoint: false, start: false, finish: false},
	{x: 1291, y: 2009, checkpoint: false, start: false, finish: false},
	{x: 1239, y: 2019, checkpoint: false, start: false, finish: false},
	{x: 1188, y: 2024, checkpoint: false, start: false, finish: false},
	{x: 1161, y: 2001, checkpoint: false, start: false, finish: false},
	{x: 1164, y: 1966, checkpoint: false, start: false, finish: false},
	{x: 1167, y: 1921, checkpoint: false, start: false, finish: false},
	{x: 1154, y: 1889, checkpoint: false, start: false, finish: false},
	{x: 1123, y: 1885, checkpoint: false, start: false, finish: false},
	{x: 1085, y: 1907, checkpoint: false, start: false, finish: false},
	{x: 1049, y: 1933, checkpoint: false, start: false, finish: false}
]);

circuits['zandvoort'] = new CircuitData('zandvoort', 130, 38, 3, Color.fromHex('#282622'), [
	{x: -1351, y: -373, checkpoint: false, start: true, finish: true},
	{x: -862, y: -1547, checkpoint: true, start: false, finish: false},
	{x: -846, y: -1581, checkpoint: false, start: false, finish: false},
	{x: -824, y: -1610, checkpoint: false, start: false, finish: false},
	{x: -796, y: -1635, checkpoint: false, start: false, finish: false},
	{x: -765, y: -1653, checkpoint: false, start: false, finish: false},
	{x: -728, y: -1662, checkpoint: false, start: false, finish: false},
	{x: -692, y: -1661, checkpoint: false, start: false, finish: false},
	{x: -656, y: -1652, checkpoint: false, start: false, finish: false},
	{x: -622, y: -1637, checkpoint: false, start: false, finish: false},

	{x: -592, y: -1616, checkpoint: false, start: false, finish: false},
	{x: -568, y: -1589, checkpoint: false, start: false, finish: false},
	{x: -552, y: -1555, checkpoint: false, start: false, finish: false},
	{x: -548, y: -1518, checkpoint: false, start: false, finish: false},
	{x: -549, y: -1481, checkpoint: false, start: false, finish: false},
	{x: -556, y: -1446, checkpoint: false, start: false, finish: false},
	{x: -568, y: -1411, checkpoint: false, start: false, finish: false},
	{x: -583, y: -1376, checkpoint: false, start: false, finish: false},
	{x: -682, y: -1136, checkpoint: true, start: false, finish: false},
	{x: -711, y: -1070, checkpoint: false, start: false, finish: false},

	{x: -736, y: -1001, checkpoint: false, start: false, finish: false},
	{x: -757, y: -930, checkpoint: false, start: false, finish: false},
	{x: -776, y: -857, checkpoint: false, start: false, finish: false},
	{x: -783, y: -822, checkpoint: false, start: false, finish: false},
	{x: -789, y: -785, checkpoint: false, start: false, finish: false},
	{x: -792, y: -749, checkpoint: false, start: false, finish: false},
	{x: -792, y: -712, checkpoint: false, start: false, finish: false},
	{x: -791, y: -565, checkpoint: false, start: false, finish: false},
	{x: -791, y: -529, checkpoint: false, start: false, finish: false},
	{x: -796, y: -493, checkpoint: false, start: false, finish: false},

	{x: -809, y: -458, checkpoint: false, start: false, finish: false},
	{x: -827, y: -426, checkpoint: false, start: false, finish: false},
	{x: -850, y: -398, checkpoint: false, start: false, finish: false},
	{x: -878, y: -374, checkpoint: false, start: false, finish: false},
	{x: -909, y: -356, checkpoint: false, start: false, finish: false},
	{x: -942, y: -342, checkpoint: false, start: false, finish: false},
	{x: -1112, y: -274, checkpoint: false, start: false, finish: false},
	{x: -1146, y: -260, checkpoint: false, start: false, finish: false},
	{x: -1179, y: -245, checkpoint: false, start: false, finish: false},
	{x: -1210, y: -225, checkpoint: false, start: false, finish: false},

	{x: -1235, y: -199, checkpoint: false, start: false, finish: false},
	{x: -1255, y: -168, checkpoint: false, start: false, finish: false},
	{x: -1262, y: -132, checkpoint: false, start: false, finish: false},
	{x: -1261, y: -95, checkpoint: false, start: false, finish: false},
	{x: -1252, y: -59, checkpoint: false, start: false, finish: false},
	{x: -1233, y: -28, checkpoint: false, start: false, finish: false},
	{x: -1207, y: -1, checkpoint: false, start: false, finish: false},
	{x: -1176, y: 17, checkpoint: false, start: false, finish: false},
	{x: -1140, y: 25, checkpoint: false, start: false, finish: false},
	{x: -1103, y: 25, checkpoint: false, start: false, finish: false},

	{x: -1067, y: 20, checkpoint: false, start: false, finish: false},
	{x: -1032, y: 10, checkpoint: false, start: false, finish: false},
	{x: -999, y: -4, checkpoint: false, start: false, finish: false},
	{x: -963, y: -19, checkpoint: false, start: false, finish: false},
	{x: -828, y: -70, checkpoint: false, start: false, finish: false},
	{x: -759, y: -93, checkpoint: true, start: false, finish: false},
	{x: -687, y: -113, checkpoint: false, start: false, finish: false},
	{x: -651, y: -120, checkpoint: false, start: false, finish: false},
	{x: -616, y: -123, checkpoint: false, start: false, finish: false},
	{x: -581, y: -126, checkpoint: false, start: false, finish: false},

	{x: -506, y: -130, checkpoint: false, start: false, finish: false},
	{x: -433, y: -133, checkpoint: false, start: false, finish: false},
	{x: -360, y: -132, checkpoint: false, start: false, finish: false},
	{x: -287, y: -127, checkpoint: false, start: false, finish: false},
	{x: -214, y: -120, checkpoint: false, start: false, finish: false},
	{x: -143, y: -106, checkpoint: false, start: false, finish: false},
	{x: -72, y: -89, checkpoint: false, start: false, finish: false},
	{x: -1, y: -72, checkpoint: false, start: false, finish: false},
	{x: 70, y: -57, checkpoint: false, start: false, finish: false},
	{x: 142, y: -46, checkpoint: false, start: false, finish: false},

	{x: 216, y: -38, checkpoint: false, start: false, finish: false},
	{x: 289, y: -37, checkpoint: false, start: false, finish: false},
	{x: 360, y: -42, checkpoint: false, start: false, finish: false},
	{x: 413, y: -54, checkpoint: false, start: false, finish: false},
	{x: 452, y: -69, checkpoint: false, start: false, finish: false},
	{x: 497, y: -94, checkpoint: false, start: false, finish: false},
	{x: 559, y: -133, checkpoint: false, start: false, finish: false},
	{x: 654, y: -189, checkpoint: false, start: false, finish: false},
	{x: 751, y: -241, checkpoint: false, start: false, finish: false},
	{x: 850, y: -285, checkpoint: false, start: false, finish: false},

	{x: 954, y: -320, checkpoint: false, start: false, finish: false},
	{x: 1061, y: -341, checkpoint: false, start: false, finish: false},
	{x: 1134, y: -347, checkpoint: false, start: false, finish: false},
	{x: 1206, y: -348, checkpoint: true, start: false, finish: false},
	{x: 1316, y: -342, checkpoint: false, start: false, finish: false},
	{x: 1426, y: -338, checkpoint: false, start: false, finish: false},
	{x: 1536, y: -333, checkpoint: false, start: false, finish: false},
	{x: 1646, y: -326, checkpoint: false, start: false, finish: false},
	{x: 1715, y: -320, checkpoint: false, start: false, finish: false},
	{x: 1755, y: -314, checkpoint: false, start: false, finish: false},

	{x: 1792, y: -305, checkpoint: false, start: false, finish: false},
	{x: 1826, y: -293, checkpoint: false, start: false, finish: false},
	{x: 1860, y: -278, checkpoint: false, start: false, finish: false},
	{x: 1893, y: -260, checkpoint: false, start: false, finish: false},
	{x: 1925, y: -236, checkpoint: false, start: false, finish: false},
	{x: 1958, y: -206, checkpoint: false, start: false, finish: false},
	{x: 1986, y: -170, checkpoint: false, start: false, finish: false},
	{x: 2012, y: -123, checkpoint: false, start: false, finish: false},
	{x: 2026, y: -68, checkpoint: false, start: false, finish: false},
	{x: 2033, y: -24, checkpoint: true, start: false, finish: false},

	{x: 2038, y: 25, checkpoint: false, start: false, finish: false},
	{x: 2038, y: 77, checkpoint: false, start: false, finish: false},
	{x: 2034, y: 135, checkpoint: false, start: false, finish: false},
	{x: 2024, y: 181, checkpoint: false, start: false, finish: false},
	{x: 2008, y: 219, checkpoint: false, start: false, finish: false},
	{x: 1983, y: 262, checkpoint: false, start: false, finish: false},
	{x: 1877, y: 416, checkpoint: false, start: false, finish: false},
	{x: 1854, y: 448, checkpoint: false, start: false, finish: false},
	{x: 1834, y: 478, checkpoint: false, start: false, finish: false},
	{x: 1814, y: 510, checkpoint: false, start: false, finish: false},

	{x: 1577, y: 961, checkpoint: false, start: false, finish: false},
	{x: 1561, y: 997, checkpoint: false, start: false, finish: false},
	{x: 1542, y: 1029, checkpoint: false, start: false, finish: false},
	{x: 1520, y: 1057, checkpoint: false, start: false, finish: false},
	{x: 1494, y: 1084, checkpoint: false, start: false, finish: false},
	{x: 1464, y: 1103, checkpoint: true, start: false, finish: false},
	{x: 1428, y: 1117, checkpoint: false, start: false, finish: false},
	{x: 1391, y: 1120, checkpoint: false, start: false, finish: false},
	{x: 1353, y: 1121, checkpoint: false, start: false, finish: false},
	{x: 1282, y: 1118, checkpoint: false, start: false, finish: false},

	{x: 1209, y: 1110, checkpoint: false, start: false, finish: false},
	{x: 1137, y: 1097, checkpoint: false, start: false, finish: false},
	{x: 1065, y: 1080, checkpoint: false, start: false, finish: false},
	{x: 995, y: 1057, checkpoint: false, start: false, finish: false},
	{x: 928, y: 1029, checkpoint: false, start: false, finish: false},
	{x: 862, y: 994, checkpoint: false, start: false, finish: false},
	{x: 801, y: 953, checkpoint: false, start: false, finish: false},
	{x: 748, y: 903, checkpoint: false, start: false, finish: false},
	{x: 708, y: 845, checkpoint: false, start: false, finish: false},
	{x: 691, y: 810, checkpoint: false, start: false, finish: false},

	{x: 683, y: 773, checkpoint: false, start: false, finish: false},
	{x: 686, y: 737, checkpoint: false, start: false, finish: false},
	{x: 707, y: 706, checkpoint: false, start: false, finish: false},
	{x: 731, y: 679, checkpoint: false, start: false, finish: false},
	{x: 760, y: 656, checkpoint: false, start: false, finish: false},
	{x: 789, y: 633, checkpoint: false, start: false, finish: false},
	{x: 820, y: 614, checkpoint: false, start: false, finish: false},
	{x: 853, y: 598, checkpoint: false, start: false, finish: false},
	{x: 888, y: 586, checkpoint: false, start: false, finish: false},
	{x: 924, y: 578, checkpoint: false, start: false, finish: false},

	{x: 960, y: 573, checkpoint: false, start: false, finish: false},
	{x: 996, y: 568, checkpoint: false, start: false, finish: false},
	{x: 1032, y: 561, checkpoint: false, start: false, finish: false},
	{x: 1068, y: 554, checkpoint: false, start: false, finish: false},
	{x: 1140, y: 539, checkpoint: false, start: false, finish: false},
	{x: 1247, y: 510, checkpoint: false, start: false, finish: false},
	{x: 1349, y: 472, checkpoint: false, start: false, finish: false},
	{x: 1413, y: 437, checkpoint: false, start: false, finish: false},
	{x: 1440, y: 412, checkpoint: false, start: false, finish: false},
	{x: 1465, y: 384, checkpoint: false, start: false, finish: false},

	{x: 1483, y: 352, checkpoint: false, start: false, finish: false},
	{x: 1498, y: 319, checkpoint: false, start: false, finish: false},
	{x: 1501, y: 283, checkpoint: false, start: false, finish: false},
	{x: 1497, y: 246, checkpoint: false, start: false, finish: false},
	{x: 1488, y: 211, checkpoint: false, start: false, finish: false},
	{x: 1470, y: 177, checkpoint: false, start: false, finish: false},
	{x: 1449, y: 147, checkpoint: false, start: false, finish: false},
	{x: 1419, y: 124, checkpoint: false, start: false, finish: false},
	{x: 1387, y: 108, checkpoint: false, start: false, finish: false},
	{x: 1352, y: 97, checkpoint: false, start: false, finish: false},

	{x: 1315, y: 90, checkpoint: false, start: false, finish: false},
	{x: 1279, y: 85, checkpoint: false, start: false, finish: false},
	{x: 1207, y: 77, checkpoint: false, start: false, finish: false},
	{x: 1133, y: 70, checkpoint: false, start: false, finish: false},
	{x: 1059, y: 65, checkpoint: false, start: false, finish: false},
	{x: 712, y: 63, checkpoint: false, start: false, finish: false},
	{x: 586, y: 72, checkpoint: false, start: false, finish: false},
	{x: 458, y: 86, checkpoint: false, start: false, finish: false},
	{x: 330, y: 108, checkpoint: false, start: false, finish: false},
	{x: 205, y: 140, checkpoint: false, start: false, finish: false},

	{x: -58, y: 217, checkpoint: false, start: false, finish: false},
	{x: -387, y: 338, checkpoint: false, start: false, finish: false},
	{x: -520, y: 398, checkpoint: false, start: false, finish: false},
	{x: -584, y: 433, checkpoint: false, start: false, finish: false},
	{x: -616, y: 450, checkpoint: false, start: false, finish: false},
	{x: -648, y: 464, checkpoint: false, start: false, finish: false},
	{x: -683, y: 474, checkpoint: false, start: false, finish: false},
	{x: -719, y: 473, checkpoint: false, start: false, finish: false},
	{x: -751, y: 456, checkpoint: false, start: false, finish: false},
	{x: -775, y: 428, checkpoint: false, start: false, finish: false},

	{x: -817, y: 366, checkpoint: false, start: false, finish: false},
	{x: -844, y: 343, checkpoint: true, start: false, finish: false},
	{x: -877, y: 326, checkpoint: false, start: false, finish: false},
	{x: -912, y: 319, checkpoint: false, start: false, finish: false},
	{x: -948, y: 323, checkpoint: false, start: false, finish: false},
	{x: -981, y: 340, checkpoint: false, start: false, finish: false},
	{x: -1011, y: 361, checkpoint: false, start: false, finish: false},
	{x: -1036, y: 387, checkpoint: false, start: false, finish: false},
	{x: -1054, y: 420, checkpoint: false, start: false, finish: false},
	{x: -1061, y: 455, checkpoint: false, start: false, finish: false},

	{x: -1060, y: 492, checkpoint: false, start: false, finish: false},
	{x: -909, y: 1362, checkpoint: false, start: false, finish: false},
	{x: -897, y: 1433, checkpoint: false, start: false, finish: false},
	{x: -892, y: 1506, checkpoint: false, start: false, finish: false},
	{x: -896, y: 1560, checkpoint: false, start: false, finish: false},
	{x: -914, y: 1613, checkpoint: false, start: false, finish: false},
	{x: -942, y: 1651, checkpoint: false, start: false, finish: false},
	{x: -975, y: 1678, checkpoint: false, start: false, finish: false},
	{x: -1022, y: 1703, checkpoint: false, start: false, finish: false},
	{x: -1073, y: 1718, checkpoint: false, start: false, finish: false},

	{x: -1124, y: 1727, checkpoint: false, start: false, finish: false},
	{x: -1187, y: 1731, checkpoint: false, start: false, finish: false},
	{x: -1298, y: 1736, checkpoint: false, start: false, finish: false},
	{x: -1409, y: 1735, checkpoint: false, start: false, finish: false},
	{x: -1518, y: 1722, checkpoint: false, start: false, finish: false},
	{x: -1624, y: 1698, checkpoint: false, start: false, finish: false},
	{x: -1725, y: 1654, checkpoint: false, start: false, finish: false},
	{x: -1807, y: 1583, checkpoint: false, start: false, finish: false},
	{x: -1848, y: 1521, checkpoint: false, start: false, finish: false},
	{x: -1884, y: 1457, checkpoint: false, start: false, finish: false},

	{x: -1916, y: 1391, checkpoint: false, start: false, finish: false},
	{x: -1940, y: 1323, checkpoint: false, start: false, finish: false},
	{x: -1951, y: 1250, checkpoint: false, start: false, finish: false},
	{x: -1952, y: 1177, checkpoint: false, start: false, finish: false},
	{x: -1947, y: 1103, checkpoint: false, start: false, finish: false},
	{x: -1928, y: 1032, checkpoint: false, start: false, finish: false},
	{x: -1903, y: 964, checkpoint: false, start: false, finish: false},
	{x: -1875, y: 896, checkpoint: false, start: false, finish: false},
	{x: -1847, y: 828, checkpoint: false, start: false, finish: false}
]);

export {circuits};
